name: food
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  appwrite: ^9.0.0
  auto_route: ^7.4.0
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  flutter_form_builder: ^9.0.0
  intl: ^0.18.1
  image_picker: ^1.0.0
  flutter_secure_storage: ^8.0.0
  uuid: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
